version: "3.3"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - target: 5432
      published: 5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data

volumes:
  data:
